import mongoose from "mongoose";

const deviceTokenSchema = new mongoose.Schema(
  {
    // Reference to the user who owns the device token
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true
    },

    // The push notification token generated by Firebase/APNs/etc.
    token: {
      type: String,
      required: true,
      unique: true, // Prevent storing the same token multiple times
      trim: true
    },

    // Platform of the device where the token is used
    platform: {
      type: String,
      enum: ["web", "android", "ios"], // Limit to known platforms
      required: true
    },

    // Optional: Device information for debugging or targeting
    deviceInfo: {
      type: String,
      default: null
    },

    // Optional: Whether token is currently active for notifications
    isActive: {
      type: Boolean,
      default: true
    },

    // Timestamp of creation (auto-generated)
    createdAt: {
      type: Date,
      default: Date.now
    },

    // Timestamp of last update (auto-updates)
    updatedAt: {
      type: Date,
      default: Date.now
    }
  },
  {
    timestamps: true // Automatically manages createdAt & updatedAt
  }
);

export default mongoose.model("DeviceToken", deviceTokenSchema);
